language: java
jdk: oraclejdk7
before_install:
    # Install base Android SDK
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
    - cat android-sdk-installer | bash /dev/stdin --install=tools,platform-tools,build-tools-19.0.3,doc-19,android-19,addon-google_apis_x86-google-19,addon-google_gdk-google-19,source-19,extra-android-support
    - source ~/.android-sdk-installer/env

    # Create and start emulator
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &

script:
    - ./wait_for_emulator